/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form SalaryCompFrame
     */
    public MainFrame() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblBrgyIcon1 = new javax.swing.JLabel();
        pnllSideBar = new javax.swing.JPanel();
        lblSystem = new javax.swing.JLabel();
        btnPayrollTab = new javax.swing.JButton();
        pnlEmployeeSubmenu = new javax.swing.JPanel();
        btnAddEmployee = new javax.swing.JButton();
        btnDelEmployee = new javax.swing.JButton();
        btnViewEmployee = new javax.swing.JButton();
        btnEmployeeManagement1 = new javax.swing.JButton();
        btnSalaryCompTab1 = new javax.swing.JButton();
        btnPayslipTab = new javax.swing.JButton();
        lblPayroll = new javax.swing.JLabel();
        lblManagement = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlSalaryComp = new javax.swing.JPanel();
        lblSCTabTitle = new javax.swing.JLabel();
        lblBrgyIcon = new javax.swing.JLabel();
        lblSCTitle = new javax.swing.JLabel();
        lblEmpID = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        txtEmpName = new javax.swing.JTextField();
        txtEmpPos = new javax.swing.JTextField();
        lblEmpPos = new javax.swing.JLabel();
        lblRatePerDay = new javax.swing.JLabel();
        lblGrossSalary = new javax.swing.JLabel();
        txtDedPAGIBIG = new javax.swing.JTextField();
        lblDaysWorked = new javax.swing.JLabel();
        btnCompute = new javax.swing.JButton();
        lblDedTax = new javax.swing.JLabel();
        lblDeductionTitle = new javax.swing.JLabel();
        txtDaysWorked = new javax.swing.JTextField();
        lblDedPAGIBIG = new javax.swing.JLabel();
        lblDedSSS = new javax.swing.JLabel();
        lblDedLoan = new javax.swing.JLabel();
        txtDedTax = new javax.swing.JTextField();
        txtDedLoan = new javax.swing.JTextField();
        txtDedSSS = new javax.swing.JTextField();
        lblTotDeductions = new javax.swing.JLabel();
        txtRatePerDay1 = new javax.swing.JTextField();
        pnlAddEmp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlDelEmp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlViewEmp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(209, 209, 209));
        setForeground(new java.awt.Color(209, 209, 209));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 251, 251));
        pnlHeader.setForeground(new java.awt.Color(255, 251, 251));
        pnlHeader.setMinimumSize(new java.awt.Dimension(1200, 110));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1440, 153));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderTitle.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblHeaderTitle.setText("BARANGAY SAN ROQUE, CAINTA, RIZAL");
        pnlHeader.add(lblHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 860, 150));

        lblBrgyIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_system/assets/placeholder.png"))); // NOI18N
        pnlHeader.add(lblBrgyIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, -1));

        pnllSideBar.setBackground(new java.awt.Color(11, 11, 69));
        pnllSideBar.setPreferredSize(new java.awt.Dimension(290, 871));
        pnllSideBar.setVerifyInputWhenFocusTarget(false);
        pnllSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSystem.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblSystem.setText("System");
        pnllSideBar.add(lblSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 250, 40));

        btnPayrollTab.setBackground(new java.awt.Color(11, 11, 69));
        btnPayrollTab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPayrollTab.setForeground(new java.awt.Color(255, 255, 255));
        btnPayrollTab.setText("Payroll");
        btnPayrollTab.setBorder(null);
        btnPayrollTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayrollTabActionPerformed(evt);
            }
        });
        pnllSideBar.add(btnPayrollTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, -1));

        pnlEmployeeSubmenu.setBackground(new java.awt.Color(14, 14, 86));
        pnlEmployeeSubmenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(14, 14, 86), 1, true));
        pnlEmployeeSubmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddEmployee.setBackground(new java.awt.Color(14, 14, 86));
        btnAddEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.setBorder(null);
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeSubmenu.add(btnAddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 250, 30));

        btnDelEmployee.setBackground(new java.awt.Color(14, 14, 86));
        btnDelEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnDelEmployee.setText("Delete Employee");
        btnDelEmployee.setBorder(null);
        btnDelEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeSubmenu.add(btnDelEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 30));

        btnViewEmployee.setBackground(new java.awt.Color(14, 14, 86));
        btnViewEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnViewEmployee.setText("View Employee");
        btnViewEmployee.setBorder(null);
        btnViewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeSubmenu.add(btnViewEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        pnllSideBar.add(pnlEmployeeSubmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 290, -1));

        btnEmployeeManagement1.setBackground(new java.awt.Color(11, 11, 69));
        btnEmployeeManagement1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEmployeeManagement1.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployeeManagement1.setText("Employee Management     ▼");
        btnEmployeeManagement1.setBorder(null);
        btnEmployeeManagement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeManagement1ActionPerformed(evt);
            }
        });
        pnllSideBar.add(btnEmployeeManagement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, -1));

        btnSalaryCompTab1.setBackground(new java.awt.Color(11, 11, 69));
        btnSalaryCompTab1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalaryCompTab1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalaryCompTab1.setText("Salary Computation");
        btnSalaryCompTab1.setBorder(null);
        btnSalaryCompTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryCompTab1ActionPerformed(evt);
            }
        });
        pnllSideBar.add(btnSalaryCompTab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, -1));

        btnPayslipTab.setBackground(new java.awt.Color(11, 11, 69));
        btnPayslipTab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPayslipTab.setForeground(new java.awt.Color(255, 255, 255));
        btnPayslipTab.setText("Payslip");
        btnPayslipTab.setBorder(null);
        btnPayslipTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayslipTabActionPerformed(evt);
            }
        });
        pnllSideBar.add(btnPayslipTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 290, -1));

        lblPayroll.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblPayroll.setForeground(new java.awt.Color(255, 255, 255));
        lblPayroll.setText("Payroll");
        pnllSideBar.add(lblPayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 40));

        lblManagement.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblManagement.setForeground(new java.awt.Color(255, 255, 255));
        lblManagement.setText("Management");
        pnllSideBar.add(lblManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 40));

        getContentPane().add(pnllSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, -1, 530));

        lblSCTabTitle.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        lblSCTabTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSCTabTitle.setText("BARANGAY EMPLOYEE SALARY COMPUTATION");

        lblBrgyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_system/assets/placeholder.png"))); // NOI18N

        lblSCTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblSCTitle.setText("Computation of Salary");

        lblEmpID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpID.setText("Employee ID:");

        lblEmpName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpName.setText("Employee Name:");

        txtEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpIDActionPerformed(evt);
            }
        });

        txtEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNameActionPerformed(evt);
            }
        });

        txtEmpPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpPosActionPerformed(evt);
            }
        });

        lblEmpPos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpPos.setText("Employee Position:");

        lblRatePerDay.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblRatePerDay.setText("Rate Per Day:");

        lblGrossSalary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGrossSalary.setText("Gross Salary:");

        txtDedPAGIBIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDedPAGIBIGActionPerformed(evt);
            }
        });

        lblDaysWorked.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDaysWorked.setText("<html>Number of Days<br>Worked:</html>");

        btnCompute.setBackground(new java.awt.Color(11, 11, 69));
        btnCompute.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCompute.setForeground(new java.awt.Color(255, 255, 255));
        btnCompute.setText("Compute");

        lblDedTax.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDedTax.setText("Tax (3% of Gross Salary):");

        lblDeductionTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblDeductionTitle.setForeground(new java.awt.Color(210, 4, 45));
        lblDeductionTitle.setText("Deductions");

        txtDaysWorked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDaysWorkedActionPerformed(evt);
            }
        });

        lblDedPAGIBIG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDedPAGIBIG.setText("PAG-IBIG:");

        lblDedSSS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDedSSS.setText("SSS:");

        lblDedLoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDedLoan.setText("Loan:");

        txtDedTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDedTaxActionPerformed(evt);
            }
        });

        txtDedLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDedLoanActionPerformed(evt);
            }
        });

        txtDedSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDedSSSActionPerformed(evt);
            }
        });

        lblTotDeductions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotDeductions.setText("Total Deductions:");

        txtRatePerDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRatePerDay1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSalaryCompLayout = new javax.swing.GroupLayout(pnlSalaryComp);
        pnlSalaryComp.setLayout(pnlSalaryCompLayout);
        pnlSalaryCompLayout.setHorizontalGroup(
            pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalaryCompLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSalaryCompLayout.createSequentialGroup()
                        .addComponent(lblBrgyIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSCTabTitle))
                    .addGroup(pnlSalaryCompLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRatePerDay)
                            .addComponent(lblEmpName)
                            .addComponent(lblEmpID)
                            .addComponent(lblEmpPos)
                            .addComponent(lblDaysWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGrossSalary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalaryCompLayout.createSequentialGroup()
                                .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDaysWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmpPos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRatePerDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDedTax)
                                    .addComponent(lblDedPAGIBIG)
                                    .addComponent(lblDedSSS)
                                    .addComponent(lblDedLoan)))
                            .addComponent(lblTotDeductions, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDedPAGIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDedTax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDedLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDedSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalaryCompLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCompute, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
            .addGroup(pnlSalaryCompLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblSCTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDeductionTitle)
                .addGap(74, 74, 74))
        );
        pnlSalaryCompLayout.setVerticalGroup(
            pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalaryCompLayout.createSequentialGroup()
                .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSalaryCompLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblBrgyIcon))
                    .addGroup(pnlSalaryCompLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblSCTabTitle)))
                .addGap(18, 18, 18)
                .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSCTitle)
                    .addComponent(lblDeductionTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSalaryCompLayout.createSequentialGroup()
                        .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDedTax)
                            .addComponent(txtDedTax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDedPAGIBIG)
                            .addComponent(txtDedPAGIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDedSSS)
                            .addComponent(txtDedSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDedLoan)
                            .addComponent(txtDedLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSalaryCompLayout.createSequentialGroup()
                        .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSalaryCompLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblEmpID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmpName)
                                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmpPos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpPos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRatePerDay)
                                    .addComponent(txtRatePerDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(lblDaysWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalaryCompLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDaysWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(pnlSalaryCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrossSalary)
                    .addComponent(lblTotDeductions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnCompute, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        txtEmpID.getAccessibleContext().setAccessibleName("employeeID");
        txtEmpName.getAccessibleContext().setAccessibleName("employeeName");
        btnCompute.getAccessibleContext().setAccessibleName("compute");

        jTabbedPane1.addTab("SalaryComputation", pnlSalaryComp);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel2.setText("Employee Registration");
        pnlAddEmp.add(jLabel2);

        jTabbedPane1.addTab("AddEmployee", pnlAddEmp);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel3.setText("Archive Employee");
        pnlDelEmp.add(jLabel3);

        jTabbedPane1.addTab("ArchiveEmployee", pnlDelEmp);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel4.setText("View Employee");
        pnlViewEmp.add(jLabel4);

        jTabbedPane1.addTab("ViewEmployee", pnlViewEmp);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 735, 570));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1038, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayrollTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayrollTabActionPerformed
        // TODO add your handling code here:
        // Open the Payroll popup window
        java.awt.EventQueue.invokeLater(() -> {
            PayrollPopup popup = new PayrollPopup();
            popup.setLocationRelativeTo(this);
            popup.setVisible(true);
        });
    }//GEN-LAST:event_btnPayrollTabActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnEmployeeManagement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeManagement1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeeManagement1ActionPerformed

    private void btnSalaryCompTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryCompTab1ActionPerformed
        // TODO add your handling code here:
        
    jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnSalaryCompTab1ActionPerformed

    private void btnPayslipTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayslipTabActionPerformed
        // TODO add your handling code here:
        // Open the Payslip popup window
        java.awt.EventQueue.invokeLater(() -> {
            PayslipPopup popup = new PayslipPopup();
            popup.setLocationRelativeTo(this);
            popup.setVisible(true);
        });
    }//GEN-LAST:event_btnPayslipTabActionPerformed

    private void btnViewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeeActionPerformed
        // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnViewEmployeeActionPerformed

    private void btnDelEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelEmployeeActionPerformed
        // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnDelEmployeeActionPerformed

    private void txtEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNameActionPerformed

    private void txtEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpIDActionPerformed

    private void txtEmpPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpPosActionPerformed

    private void txtDedPAGIBIGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDedPAGIBIGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedPAGIBIGActionPerformed

    private void txtDaysWorkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDaysWorkedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDaysWorkedActionPerformed

    private void txtDedTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDedTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedTaxActionPerformed

    private void txtDedLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDedLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedLoanActionPerformed

    private void txtDedSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDedSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedSSSActionPerformed

    private void txtRatePerDay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRatePerDay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatePerDay1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnCompute;
    private javax.swing.JButton btnDelEmployee;
    private javax.swing.JButton btnEmployeeManagement1;
    private javax.swing.JButton btnPayrollTab;
    private javax.swing.JButton btnPayslipTab;
    private javax.swing.JButton btnSalaryCompTab1;
    private javax.swing.JButton btnViewEmployee;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBrgyIcon;
    private javax.swing.JLabel lblBrgyIcon1;
    private javax.swing.JLabel lblDaysWorked;
    private javax.swing.JLabel lblDedLoan;
    private javax.swing.JLabel lblDedPAGIBIG;
    private javax.swing.JLabel lblDedSSS;
    private javax.swing.JLabel lblDedTax;
    private javax.swing.JLabel lblDeductionTitle;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblEmpName;
    private javax.swing.JLabel lblEmpPos;
    private javax.swing.JLabel lblGrossSalary;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblManagement;
    private javax.swing.JLabel lblPayroll;
    private javax.swing.JLabel lblRatePerDay;
    private javax.swing.JLabel lblSCTabTitle;
    private javax.swing.JLabel lblSCTitle;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel lblTotDeductions;
    private javax.swing.JPanel pnlAddEmp;
    private javax.swing.JPanel pnlDelEmp;
    private javax.swing.JPanel pnlEmployeeSubmenu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlSalaryComp;
    private javax.swing.JPanel pnlViewEmp;
    private javax.swing.JPanel pnllSideBar;
    private javax.swing.JTextField txtDaysWorked;
    private javax.swing.JTextField txtDedLoan;
    private javax.swing.JTextField txtDedPAGIBIG;
    private javax.swing.JTextField txtDedSSS;
    private javax.swing.JTextField txtDedTax;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtEmpPos;
    private javax.swing.JTextField txtRatePerDay1;
    // End of variables declaration//GEN-END:variables
}
