/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form SalaryCompFrame
     */
    public MainFrame() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblBrgyIcon1 = new javax.swing.JLabel();
        pnllSideBar = new javax.swing.JPanel();
        lblSystem = new javax.swing.JLabel();
        btnPayrollTab = new javax.swing.JButton();
        pnlEmployeeSubmenu = new javax.swing.JPanel();
        btnAddEmployee = new javax.swing.JButton();
        btnDelEmployee = new javax.swing.JButton();
        btnViewEmployee = new javax.swing.JButton();
        btnEmployeeManagement1 = new javax.swing.JButton();
        btnSalaryCompTab1 = new javax.swing.JButton();
        btnPayslipTab = new javax.swing.JButton();
        lblPayroll = new javax.swing.JLabel();
        lblManagement = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAddEmp = new javax.swing.JPanel();
        pnlEmpRegInner = new javax.swing.JPanel();
        lblBrgyIcon2 = new javax.swing.JLabel();
        lblERTabTitle = new javax.swing.JLabel();
        lblRegEmpName = new javax.swing.JLabel();
        txtRegEmpName = new javax.swing.JTextField();
        lblRegPosition = new javax.swing.JLabel();
        txtRegPosition = new javax.swing.JTextField();
        lblRegRatePerDay = new javax.swing.JLabel();
        lblRegDept3 = new javax.swing.JLabel();
        formtxtContact = new javax.swing.JFormattedTextField();
        btnAddEmp = new javax.swing.JButton();
        formtxtRate = new javax.swing.JFormattedTextField();
        txtRegDept1 = new javax.swing.JTextField();
        lblRegDept1 = new javax.swing.JLabel();
        txtRegAddress = new javax.swing.JTextField();
        lblRegDept = new javax.swing.JLabel();
        pnlDelEmp = new javax.swing.JPanel();
        pnlEmpDeleteInner = new javax.swing.JPanel();
        lblBrgyIcon3 = new javax.swing.JLabel();
        lblDETabTitle = new javax.swing.JLabel();
        lblDelEmpName = new javax.swing.JLabel();
        txtDelEmpName = new javax.swing.JTextField();
        lblDelPosition = new javax.swing.JLabel();
        txtDelPosition = new javax.swing.JTextField();
        lblDelRatePerDay = new javax.swing.JLabel();
        lblDelAddress = new javax.swing.JLabel();
        formtxtDelContact = new javax.swing.JFormattedTextField();
        btnDelEmp = new javax.swing.JButton();
        formtxtDelRate = new javax.swing.JFormattedTextField();
        txtDelDept = new javax.swing.JTextField();
        lblDelDept = new javax.swing.JLabel();
        txtDelAddress = new javax.swing.JTextField();
        lblDelContact = new javax.swing.JLabel();
        pnlViewEmp = new javax.swing.JPanel();
        pnlEmpViewInner = new javax.swing.JPanel();
        lblBrgyIcon4 = new javax.swing.JLabel();
        lblViewEmpName = new javax.swing.JLabel();
        btnSearchEmp = new javax.swing.JButton();
        lblVETabTitle = new javax.swing.JLabel();
        formtxtViewEmpID = new javax.swing.JFormattedTextField();
        pnlSalaryComp = new javax.swing.JPanel();
        pnlEmpViewInner1 = new javax.swing.JPanel();
        lblSCTitle = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        lblDaysWorked = new javax.swing.JLabel();
        lblDedTax = new javax.swing.JLabel();
        lblDeductionTitle = new javax.swing.JLabel();
        lblDedLoan = new javax.swing.JLabel();
        lblTotDeductions = new javax.swing.JLabel();
        lblSCTabTitle2 = new javax.swing.JLabel();
        lblBrgyIcon = new javax.swing.JLabel();
        lblSCTabTitle1 = new javax.swing.JLabel();
        lblDedSSS = new javax.swing.JLabel();
        lblDedPAGIBIG = new javax.swing.JLabel();
        lblGrossSalary = new javax.swing.JLabel();
        lblEmpPos = new javax.swing.JLabel();
        lblRatePerDay = new javax.swing.JLabel();
        lblEmpID = new javax.swing.JLabel();
        txtDedPAGIBIG = new javax.swing.JTextField();
        txtEmpID = new javax.swing.JTextField();
        txtEmpName = new javax.swing.JTextField();
        txtEmpPos = new javax.swing.JTextField();
        txtDaysWorked = new javax.swing.JTextField();
        txtDedTax = new javax.swing.JTextField();
        txtRatePerDay1 = new javax.swing.JTextField();
        txtDedSSS = new javax.swing.JTextField();
        txtDedLoan = new javax.swing.JTextField();
        btnCompute = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(209, 209, 209));
        setForeground(new java.awt.Color(209, 209, 209));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 251, 251));
        pnlHeader.setForeground(new java.awt.Color(255, 251, 251));
        pnlHeader.setMinimumSize(new java.awt.Dimension(1200, 110));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1440, 153));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeaderTitle.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblHeaderTitle.setText("BARANGAY SAN ROQUE, CAINTA, RIZAL");
        pnlHeader.add(lblHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 860, 150));

        lblBrgyIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_system/assets/placeholder.png"))); // NOI18N
        pnlHeader.add(lblBrgyIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, -1));

        pnllSideBar.setBackground(new java.awt.Color(11, 11, 69));
        pnllSideBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnllSideBar.setPreferredSize(new java.awt.Dimension(290, 871));
        pnllSideBar.setVerifyInputWhenFocusTarget(false);
        pnllSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSystem.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblSystem.setText("System");
        pnllSideBar.add(lblSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 250, 40));

        btnPayrollTab.setBackground(new java.awt.Color(11, 11, 69));
        btnPayrollTab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPayrollTab.setForeground(new java.awt.Color(255, 255, 255));
        btnPayrollTab.setText("Payroll");
        btnPayrollTab.setBorder(null);
        btnPayrollTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayrollTabActionPerformed(evt);
            }
        });
        pnllSideBar.add(btnPayrollTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, 30));

        pnlEmployeeSubmenu.setBackground(new java.awt.Color(14, 14, 86));
        pnlEmployeeSubmenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(14, 14, 86), 1, true));
        pnlEmployeeSubmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddEmployee.setBackground(new java.awt.Color(14, 14, 86));
        btnAddEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.setBorder(null);
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeSubmenu.add(btnAddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 250, 30));

        btnDelEmployee.setBackground(new java.awt.Color(14, 14, 86));
        btnDelEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnDelEmployee.setText("Delete Employee");
        btnDelEmployee.setBorder(null);
        btnDelEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeSubmenu.add(btnDelEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 30));

        btnViewEmployee.setBackground(new java.awt.Color(14, 14, 86));
        btnViewEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnViewEmployee.setText("View Employee");
        btnViewEmployee.setBorder(null);
        btnViewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeSubmenu.add(btnViewEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        pnllSideBar.add(pnlEmployeeSubmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 290, -1));

        btnEmployeeManagement1.setBackground(new java.awt.Color(11, 11, 69));
        btnEmployeeManagement1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEmployeeManagement1.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployeeManagement1.setText("Employee Management     ▼");
        btnEmployeeManagement1.setBorder(null);
        btnEmployeeManagement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeManagement1ActionPerformed(evt);
            }
        });
        pnllSideBar.add(btnEmployeeManagement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, 30));

        btnSalaryCompTab1.setBackground(new java.awt.Color(11, 11, 69));
        btnSalaryCompTab1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalaryCompTab1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalaryCompTab1.setText("Salary Computation");
        btnSalaryCompTab1.setBorder(null);
        btnSalaryCompTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryCompTab1ActionPerformed(evt);
            }
        });
        pnllSideBar.add(btnSalaryCompTab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, 30));

        btnPayslipTab.setBackground(new java.awt.Color(11, 11, 69));
        btnPayslipTab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPayslipTab.setForeground(new java.awt.Color(255, 255, 255));
        btnPayslipTab.setText("Payslip");
        btnPayslipTab.setBorder(null);
        btnPayslipTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayslipTabActionPerformed(evt);
            }
        });
        pnllSideBar.add(btnPayslipTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 290, 30));

        lblPayroll.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblPayroll.setForeground(new java.awt.Color(255, 255, 255));
        lblPayroll.setText("Payroll");
        pnllSideBar.add(lblPayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 40));

        lblManagement.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblManagement.setForeground(new java.awt.Color(255, 255, 255));
        lblManagement.setText("Management");
        pnllSideBar.add(lblManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 40));

        getContentPane().add(pnllSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, -1, 530));

        pnlAddEmp.setBackground(new java.awt.Color(209, 209, 209));
        pnlAddEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEmpRegInner.setBackground(new java.awt.Color(250, 249, 246));
        pnlEmpRegInner.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEmpRegInner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBrgyIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_system/assets/placeholder.png"))); // NOI18N
        pnlEmpRegInner.add(lblBrgyIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lblERTabTitle.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        lblERTabTitle.setText("Employee Registration");
        pnlEmpRegInner.add(lblERTabTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        lblRegEmpName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRegEmpName.setText("Register Employee Name:");
        pnlEmpRegInner.add(lblRegEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txtRegEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegEmpNameActionPerformed(evt);
            }
        });
        pnlEmpRegInner.add(txtRegEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 200, -1));

        lblRegPosition.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRegPosition.setText("Register Position:");
        pnlEmpRegInner.add(lblRegPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        txtRegPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegPositionActionPerformed(evt);
            }
        });
        pnlEmpRegInner.add(txtRegPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 200, -1));

        lblRegRatePerDay.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRegRatePerDay.setText("Rate per Day:");
        pnlEmpRegInner.add(lblRegRatePerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, 20));

        lblRegDept3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRegDept3.setText("Home Address:");
        pnlEmpRegInner.add(lblRegDept3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        formtxtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formtxtContactActionPerformed(evt);
            }
        });
        pnlEmpRegInner.add(formtxtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 200, -1));

        btnAddEmp.setBackground(new java.awt.Color(11, 11, 69));
        btnAddEmp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmp.setText("Add Employee");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });
        pnlEmpRegInner.add(btnAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 190, -1));

        formtxtRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formtxtRateActionPerformed(evt);
            }
        });
        pnlEmpRegInner.add(formtxtRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 200, -1));

        txtRegDept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegDept1ActionPerformed(evt);
            }
        });
        pnlEmpRegInner.add(txtRegDept1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 200, -1));

        lblRegDept1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRegDept1.setText("Register Department:");
        pnlEmpRegInner.add(lblRegDept1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        txtRegAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegAddressActionPerformed(evt);
            }
        });
        pnlEmpRegInner.add(txtRegAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 200, -1));

        lblRegDept.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRegDept.setText("Contact Number: ");
        pnlEmpRegInner.add(lblRegDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        pnlAddEmp.add(pnlEmpRegInner, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 660, 480));

        jTabbedPane1.addTab("AddEmployee", pnlAddEmp);

        pnlDelEmp.setBackground(new java.awt.Color(209, 209, 209));
        pnlDelEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEmpDeleteInner.setBackground(new java.awt.Color(250, 249, 246));
        pnlEmpDeleteInner.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEmpDeleteInner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBrgyIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_system/assets/placeholder.png"))); // NOI18N
        pnlEmpDeleteInner.add(lblBrgyIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lblDETabTitle.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        lblDETabTitle.setText("Archive Employee");
        pnlEmpDeleteInner.add(lblDETabTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        lblDelEmpName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDelEmpName.setText("Employee Name:");
        pnlEmpDeleteInner.add(lblDelEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txtDelEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDelEmpNameActionPerformed(evt);
            }
        });
        pnlEmpDeleteInner.add(txtDelEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 200, -1));

        lblDelPosition.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDelPosition.setText("Employee Position:");
        pnlEmpDeleteInner.add(lblDelPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        txtDelPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDelPositionActionPerformed(evt);
            }
        });
        pnlEmpDeleteInner.add(txtDelPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 200, -1));

        lblDelRatePerDay.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDelRatePerDay.setText("Rate per Day:");
        pnlEmpDeleteInner.add(lblDelRatePerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, 20));

        lblDelAddress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDelAddress.setText("Home Address:");
        pnlEmpDeleteInner.add(lblDelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        formtxtDelContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formtxtDelContactActionPerformed(evt);
            }
        });
        pnlEmpDeleteInner.add(formtxtDelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 200, -1));

        btnDelEmp.setBackground(new java.awt.Color(11, 11, 69));
        btnDelEmp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDelEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnDelEmp.setText("Delete Employee");
        btnDelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelEmpActionPerformed(evt);
            }
        });
        pnlEmpDeleteInner.add(btnDelEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 190, -1));

        formtxtDelRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formtxtDelRateActionPerformed(evt);
            }
        });
        pnlEmpDeleteInner.add(formtxtDelRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 200, -1));

        txtDelDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDelDeptActionPerformed(evt);
            }
        });
        pnlEmpDeleteInner.add(txtDelDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 200, -1));

        lblDelDept.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDelDept.setText("Department:");
        pnlEmpDeleteInner.add(lblDelDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        txtDelAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDelAddressActionPerformed(evt);
            }
        });
        pnlEmpDeleteInner.add(txtDelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 200, -1));

        lblDelContact.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDelContact.setText("Contact Number: ");
        pnlEmpDeleteInner.add(lblDelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        pnlDelEmp.add(pnlEmpDeleteInner, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 660, 480));

        jTabbedPane1.addTab("ArchiveEmployee", pnlDelEmp);

        pnlViewEmp.setBackground(new java.awt.Color(209, 209, 209));
        pnlViewEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEmpViewInner.setBackground(new java.awt.Color(250, 249, 246));
        pnlEmpViewInner.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEmpViewInner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBrgyIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_system/assets/placeholder.png"))); // NOI18N
        pnlEmpViewInner.add(lblBrgyIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lblViewEmpName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblViewEmpName.setText("Employee ID:");
        pnlEmpViewInner.add(lblViewEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        btnSearchEmp.setBackground(new java.awt.Color(11, 11, 69));
        btnSearchEmp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSearchEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchEmp.setText("Search Employee");
        btnSearchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEmpActionPerformed(evt);
            }
        });
        pnlEmpViewInner.add(btnSearchEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 190, 30));

        lblVETabTitle.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        lblVETabTitle.setText("View Employee");
        pnlEmpViewInner.add(lblVETabTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));
        pnlEmpViewInner.add(formtxtViewEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, -1));

        pnlViewEmp.add(pnlEmpViewInner, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 660, 480));

        jTabbedPane1.addTab("ViewEmployee", pnlViewEmp);

        pnlSalaryComp.setBackground(new java.awt.Color(209, 209, 209));
        pnlSalaryComp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEmpViewInner1.setBackground(new java.awt.Color(250, 249, 246));
        pnlEmpViewInner1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEmpViewInner1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSCTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblSCTitle.setText("Computation of Salary");
        pnlEmpViewInner1.add(lblSCTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblEmpName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpName.setText("Employee Name:");
        pnlEmpViewInner1.add(lblEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lblDaysWorked.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDaysWorked.setText("<html>Number of Days<br>Worked:</html>");
        pnlEmpViewInner1.add(lblDaysWorked, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        lblDedTax.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDedTax.setText("Tax (3% of Gross Salary):");
        pnlEmpViewInner1.add(lblDedTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        lblDeductionTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblDeductionTitle.setForeground(new java.awt.Color(210, 4, 45));
        lblDeductionTitle.setText("Deductions");
        pnlEmpViewInner1.add(lblDeductionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        lblDedLoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDedLoan.setText("Loan:");
        pnlEmpViewInner1.add(lblDedLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        lblTotDeductions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotDeductions.setText("Total Deductions:");
        pnlEmpViewInner1.add(lblTotDeductions, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        lblSCTabTitle2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblSCTabTitle2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSCTabTitle2.setText("COMPUTATION");
        pnlEmpViewInner1.add(lblSCTabTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        lblBrgyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_system/assets/placeholder.png"))); // NOI18N
        lblBrgyIcon.setPreferredSize(new java.awt.Dimension(110, 110));
        pnlEmpViewInner1.add(lblBrgyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblSCTabTitle1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblSCTabTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSCTabTitle1.setText("BARANGAY EMPLOYEE SALARY ");
        pnlEmpViewInner1.add(lblSCTabTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        lblDedSSS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDedSSS.setText("SSS:");
        pnlEmpViewInner1.add(lblDedSSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        lblDedPAGIBIG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDedPAGIBIG.setText("PAG-IBIG:");
        pnlEmpViewInner1.add(lblDedPAGIBIG, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        lblGrossSalary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGrossSalary.setText("Gross Salary:");
        pnlEmpViewInner1.add(lblGrossSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        lblEmpPos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpPos.setText("Employee Position:");
        pnlEmpViewInner1.add(lblEmpPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        lblRatePerDay.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblRatePerDay.setText("Rate Per Day:");
        pnlEmpViewInner1.add(lblRatePerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        lblEmpID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpID.setText("Employee ID:");
        pnlEmpViewInner1.add(lblEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtDedPAGIBIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDedPAGIBIGActionPerformed(evt);
            }
        });
        pnlEmpViewInner1.add(txtDedPAGIBIG, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 150, 25));

        txtEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpIDActionPerformed(evt);
            }
        });
        pnlEmpViewInner1.add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, 25));
        txtEmpID.getAccessibleContext().setAccessibleName("employeeID");

        txtEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNameActionPerformed(evt);
            }
        });
        pnlEmpViewInner1.add(txtEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, 25));
        txtEmpName.getAccessibleContext().setAccessibleName("employeeName");

        txtEmpPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpPosActionPerformed(evt);
            }
        });
        pnlEmpViewInner1.add(txtEmpPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 150, 25));

        txtDaysWorked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDaysWorkedActionPerformed(evt);
            }
        });
        pnlEmpViewInner1.add(txtDaysWorked, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 150, 25));

        txtDedTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDedTaxActionPerformed(evt);
            }
        });
        pnlEmpViewInner1.add(txtDedTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 150, 25));

        txtRatePerDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRatePerDay1ActionPerformed(evt);
            }
        });
        pnlEmpViewInner1.add(txtRatePerDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 150, 25));

        txtDedSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDedSSSActionPerformed(evt);
            }
        });
        pnlEmpViewInner1.add(txtDedSSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 150, 25));

        txtDedLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDedLoanActionPerformed(evt);
            }
        });
        pnlEmpViewInner1.add(txtDedLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 150, -1));

        btnCompute.setBackground(new java.awt.Color(11, 11, 69));
        btnCompute.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCompute.setForeground(new java.awt.Color(255, 255, 255));
        btnCompute.setText("Compute");
        btnCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeActionPerformed(evt);
            }
        });
        pnlEmpViewInner1.add(btnCompute, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 132, 35));
        btnCompute.getAccessibleContext().setAccessibleName("compute");

        pnlSalaryComp.add(pnlEmpViewInner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 660, 480));

        jTabbedPane1.addTab("SalaryComputation", pnlSalaryComp);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 735, 570));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1038, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayrollTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayrollTabActionPerformed
        // TODO add your handling code here:
        // Open the Payroll popup window
        java.awt.EventQueue.invokeLater(() -> {
            PayrollPopup popup = new PayrollPopup();
            popup.setLocationRelativeTo(this);
            popup.setVisible(true);
        });
    }//GEN-LAST:event_btnPayrollTabActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnEmployeeManagement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeManagement1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeeManagement1ActionPerformed

    private void btnSalaryCompTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryCompTab1ActionPerformed
        // TODO add your handling code here:
        
    jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnSalaryCompTab1ActionPerformed

    private void btnPayslipTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayslipTabActionPerformed
        // TODO add your handling code here:
        // Open the Payslip popup window
        java.awt.EventQueue.invokeLater(() -> {
            PayslipPopup popup = new PayslipPopup();
            popup.setLocationRelativeTo(this);
            popup.setVisible(true);
        });
    }//GEN-LAST:event_btnPayslipTabActionPerformed

    private void btnViewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeeActionPerformed
        // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnViewEmployeeActionPerformed

    private void btnDelEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelEmployeeActionPerformed
        // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnDelEmployeeActionPerformed

    private void txtEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNameActionPerformed

    private void txtEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpIDActionPerformed

    private void txtEmpPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpPosActionPerformed

    private void txtDedPAGIBIGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDedPAGIBIGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedPAGIBIGActionPerformed

    private void txtDaysWorkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDaysWorkedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDaysWorkedActionPerformed

    private void txtDedTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDedTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedTaxActionPerformed

    private void txtDedLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDedLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedLoanActionPerformed

    private void txtDedSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDedSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedSSSActionPerformed

    private void txtRatePerDay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRatePerDay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatePerDay1ActionPerformed

    private void txtRegEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegEmpNameActionPerformed

    private void formtxtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formtxtRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formtxtRateActionPerformed

    private void txtRegDept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegDept1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegDept1ActionPerformed

    private void txtRegPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegPositionActionPerformed

    private void txtRegAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegAddressActionPerformed

    private void formtxtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formtxtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formtxtContactActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddEmpActionPerformed

    private void txtDelEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDelEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDelEmpNameActionPerformed

    private void txtDelPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDelPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDelPositionActionPerformed

    private void formtxtDelContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formtxtDelContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formtxtDelContactActionPerformed

    private void btnDelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelEmpActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_btnDelEmpActionPerformed

    private void formtxtDelRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formtxtDelRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formtxtDelRateActionPerformed

    private void txtDelDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDelDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDelDeptActionPerformed

    private void txtDelAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDelAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDelAddressActionPerformed

    private void btnSearchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchEmpActionPerformed

    private void btnComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComputeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnCompute;
    private javax.swing.JButton btnDelEmp;
    private javax.swing.JButton btnDelEmployee;
    private javax.swing.JButton btnEmployeeManagement1;
    private javax.swing.JButton btnPayrollTab;
    private javax.swing.JButton btnPayslipTab;
    private javax.swing.JButton btnSalaryCompTab1;
    private javax.swing.JButton btnSearchEmp;
    private javax.swing.JButton btnViewEmployee;
    private javax.swing.JFormattedTextField formtxtContact;
    private javax.swing.JFormattedTextField formtxtDelContact;
    private javax.swing.JFormattedTextField formtxtDelRate;
    private javax.swing.JFormattedTextField formtxtRate;
    private javax.swing.JFormattedTextField formtxtViewEmpID;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBrgyIcon;
    private javax.swing.JLabel lblBrgyIcon1;
    private javax.swing.JLabel lblBrgyIcon2;
    private javax.swing.JLabel lblBrgyIcon3;
    private javax.swing.JLabel lblBrgyIcon4;
    private javax.swing.JLabel lblDETabTitle;
    private javax.swing.JLabel lblDaysWorked;
    private javax.swing.JLabel lblDedLoan;
    private javax.swing.JLabel lblDedPAGIBIG;
    private javax.swing.JLabel lblDedSSS;
    private javax.swing.JLabel lblDedTax;
    private javax.swing.JLabel lblDeductionTitle;
    private javax.swing.JLabel lblDelAddress;
    private javax.swing.JLabel lblDelContact;
    private javax.swing.JLabel lblDelDept;
    private javax.swing.JLabel lblDelEmpName;
    private javax.swing.JLabel lblDelPosition;
    private javax.swing.JLabel lblDelRatePerDay;
    private javax.swing.JLabel lblERTabTitle;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblEmpName;
    private javax.swing.JLabel lblEmpPos;
    private javax.swing.JLabel lblGrossSalary;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblManagement;
    private javax.swing.JLabel lblPayroll;
    private javax.swing.JLabel lblRatePerDay;
    private javax.swing.JLabel lblRegDept;
    private javax.swing.JLabel lblRegDept1;
    private javax.swing.JLabel lblRegDept3;
    private javax.swing.JLabel lblRegEmpName;
    private javax.swing.JLabel lblRegPosition;
    private javax.swing.JLabel lblRegRatePerDay;
    private javax.swing.JLabel lblSCTabTitle1;
    private javax.swing.JLabel lblSCTabTitle2;
    private javax.swing.JLabel lblSCTitle;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel lblTotDeductions;
    private javax.swing.JLabel lblVETabTitle;
    private javax.swing.JLabel lblViewEmpName;
    private javax.swing.JPanel pnlAddEmp;
    private javax.swing.JPanel pnlDelEmp;
    private javax.swing.JPanel pnlEmpDeleteInner;
    private javax.swing.JPanel pnlEmpRegInner;
    private javax.swing.JPanel pnlEmpViewInner;
    private javax.swing.JPanel pnlEmpViewInner1;
    private javax.swing.JPanel pnlEmployeeSubmenu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlSalaryComp;
    private javax.swing.JPanel pnlViewEmp;
    private javax.swing.JPanel pnllSideBar;
    private javax.swing.JTextField txtDaysWorked;
    private javax.swing.JTextField txtDedLoan;
    private javax.swing.JTextField txtDedPAGIBIG;
    private javax.swing.JTextField txtDedSSS;
    private javax.swing.JTextField txtDedTax;
    private javax.swing.JTextField txtDelAddress;
    private javax.swing.JTextField txtDelDept;
    private javax.swing.JTextField txtDelEmpName;
    private javax.swing.JTextField txtDelPosition;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtEmpPos;
    private javax.swing.JTextField txtRatePerDay1;
    private javax.swing.JTextField txtRegAddress;
    private javax.swing.JTextField txtRegDept1;
    private javax.swing.JTextField txtRegEmpName;
    private javax.swing.JTextField txtRegPosition;
    // End of variables declaration//GEN-END:variables
}
