/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Ong
 */
public class PayrollPopup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PayrollPopup.class.getName());

    /**
     * Creates new form PayrollPopup
     */
    public PayrollPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSystemLogo = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitleTop = new javax.swing.JLabel();
        lblTitleMid = new javax.swing.JLabel();
        lblTitleBot = new javax.swing.JLabel();
        pnlPayrollTitle = new javax.swing.JPanel();
        lblPayrollTitle = new javax.swing.JLabel();
        lblPayPeriod = new javax.swing.JLabel();
        lblPayrollDesc1 = new javax.swing.JLabel();
        lblPayrollDesc2 = new javax.swing.JLabel();
        pnlPayrollTable = new javax.swing.JPanel();
        scrpanePayrollTable = new javax.swing.JScrollPane();
        tblPayrollTable = new javax.swing.JTable();
        pnlFooter = new javax.swing.JPanel();
        pnlFooterLeft = new javax.swing.JPanel();
        lblFooterL1 = new javax.swing.JLabel();
        lblFooterL2 = new javax.swing.JLabel();
        lblFooterL3 = new javax.swing.JLabel();
        lblFooterL4 = new javax.swing.JLabel();
        lblFooterLTreasurer = new javax.swing.JLabel();
        lblFooterLPnngBrgy = new javax.swing.JLabel();
        pnlFooterRight = new javax.swing.JPanel();
        lblFooterR1 = new javax.swing.JLabel();
        lblFooterR2 = new javax.swing.JLabel();
        lblFooterR3 = new javax.swing.JLabel();
        lblFooterR4 = new javax.swing.JLabel();
        lblFooterRTreasurer = new javax.swing.JLabel();
        btnPayrollBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payroll");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSystemLogo.setText("System Logo");

        lblTitleTop.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        lblTitleTop.setText("Republic of the Philippines");

        lblTitleMid.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        lblTitleMid.setText("Barangay San Roque");

        lblTitleBot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitleBot.setText("Cainta, Rizal");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitleTop))
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblTitleMid))
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lblTitleBot)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleTop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleMid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleBot)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(lblSystemLogo)
                .addGap(116, 116, 116)
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(553, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSystemLogo)
                .addGap(57, 57, 57))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 130));

        lblPayrollTitle.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        lblPayrollTitle.setText("Employee Payroll");

        lblPayPeriod.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPayPeriod.setText("PAY PERIOD: [MM,DD,YY] - [MM,DD,YY]");

        lblPayrollDesc1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPayrollDesc1.setText("We hereby acknowledge to have received from (Brgy. Treasurer), Treasurer of Barangay Government of San Roque, Cainta, Rizal, the sums herein specified opposite or names, ");

        lblPayrollDesc2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPayrollDesc2.setText("respective the same being fit compensation for officials benefit - medical benifit to the correctness of which we severally certify.");

        javax.swing.GroupLayout pnlPayrollTitleLayout = new javax.swing.GroupLayout(pnlPayrollTitle);
        pnlPayrollTitle.setLayout(pnlPayrollTitleLayout);
        pnlPayrollTitleLayout.setHorizontalGroup(
            pnlPayrollTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPayrollTitleLayout.createSequentialGroup()
                .addGroup(pnlPayrollTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPayrollTitleLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(lblPayrollDesc1))
                    .addGroup(pnlPayrollTitleLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(lblPayrollDesc2))
                    .addGroup(pnlPayrollTitleLayout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(lblPayrollTitle))
                    .addGroup(pnlPayrollTitleLayout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(lblPayPeriod)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        pnlPayrollTitleLayout.setVerticalGroup(
            pnlPayrollTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPayrollTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPayrollTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPayPeriod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPayrollDesc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPayrollDesc2)
                .addContainerGap())
        );

        getContentPane().add(pnlPayrollTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 1530, 120));

        tblPayrollTable.setForeground(new java.awt.Color(36, 36, 36));
        tblPayrollTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Name of Employees", "Position", "Rate per Month (PHP)", "Amount Accrued for the Period", "Deductions", "Amount Due (PHP)", "Amount Paid in Cash", "Signature of Payee"
            }
        ));
        tblPayrollTable.setRowHeight(45);
        tblPayrollTable.setShowGrid(false);
        scrpanePayrollTable.setViewportView(tblPayrollTable);

        javax.swing.GroupLayout pnlPayrollTableLayout = new javax.swing.GroupLayout(pnlPayrollTable);
        pnlPayrollTable.setLayout(pnlPayrollTableLayout);
        pnlPayrollTableLayout.setHorizontalGroup(
            pnlPayrollTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPayrollTableLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(scrpanePayrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pnlPayrollTableLayout.setVerticalGroup(
            pnlPayrollTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPayrollTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpanePayrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPayrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1530, 270));

        lblFooterL1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterL1.setText("I HEREBY CERTIFY on my official oath that the");

        lblFooterL2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterL2.setText("above PAYROLL is correct and hereby approved");

        lblFooterL3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterL3.setText("from the appropriation indicated.");

        lblFooterL4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterL4.setText("APPROVED:");

        lblFooterLTreasurer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterLTreasurer.setText("Brgy. Treasurer");

        lblFooterLPnngBrgy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterLPnngBrgy.setText("Punong Barangay");

        javax.swing.GroupLayout pnlFooterLeftLayout = new javax.swing.GroupLayout(pnlFooterLeft);
        pnlFooterLeft.setLayout(pnlFooterLeftLayout);
        pnlFooterLeftLayout.setHorizontalGroup(
            pnlFooterLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLeftLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblFooterLTreasurer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFooterLPnngBrgy)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFooterL3)
                .addGap(126, 126, 126))
            .addGroup(pnlFooterLeftLayout.createSequentialGroup()
                .addGroup(pnlFooterLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFooterLeftLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(pnlFooterLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFooterL2)
                            .addComponent(lblFooterL1)))
                    .addGroup(pnlFooterLeftLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lblFooterL4)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        pnlFooterLeftLayout.setVerticalGroup(
            pnlFooterLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLeftLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblFooterL1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFooterL2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFooterL3)
                .addGap(12, 12, 12)
                .addComponent(lblFooterL4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlFooterLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFooterLPnngBrgy)
                    .addComponent(lblFooterLTreasurer))
                .addContainerGap())
        );

        lblFooterR1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterR1.setText("I HEREBY CERTIFY on my official oath that each employee whose name appears on the above");

        lblFooterR2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterR2.setText("payroll have been paid in cash or check, and in no other mode, the amount shown under column");

        lblFooterR3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterR3.setText("“Amount Due” above opposite his/her name. The total of the payments made by means of this");

        lblFooterR4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterR4.setText("payroll amount (Amount)");

        lblFooterRTreasurer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFooterRTreasurer.setText("Barangay Treasurer");

        btnPayrollBack.setBackground(new java.awt.Color(11, 11, 69));
        btnPayrollBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPayrollBack.setForeground(new java.awt.Color(255, 255, 255));
        btnPayrollBack.setText("BACK");
        btnPayrollBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayrollBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterRightLayout = new javax.swing.GroupLayout(pnlFooterRight);
        pnlFooterRight.setLayout(pnlFooterRightLayout);
        pnlFooterRightLayout.setHorizontalGroup(
            pnlFooterRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterRightLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblFooterRTreasurer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPayrollBack, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(pnlFooterRightLayout.createSequentialGroup()
                .addGroup(pnlFooterRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFooterRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlFooterRightLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblFooterR1))
                        .addGroup(pnlFooterRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFooterRightLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblFooterR3))
                            .addComponent(lblFooterR2)))
                    .addGroup(pnlFooterRightLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(lblFooterR4)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlFooterRightLayout.setVerticalGroup(
            pnlFooterRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterRightLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblFooterR1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFooterR2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFooterR3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFooterRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFooterRightLayout.createSequentialGroup()
                        .addComponent(lblFooterR4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPayrollBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFooterRTreasurer))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(pnlFooterLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(pnlFooterRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addComponent(pnlFooterLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFooterRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        getContentPane().add(pnlFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1530, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayrollBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayrollBackActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayrollBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PayrollPopup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayrollBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFooterL1;
    private javax.swing.JLabel lblFooterL2;
    private javax.swing.JLabel lblFooterL3;
    private javax.swing.JLabel lblFooterL4;
    private javax.swing.JLabel lblFooterLPnngBrgy;
    private javax.swing.JLabel lblFooterLTreasurer;
    private javax.swing.JLabel lblFooterR1;
    private javax.swing.JLabel lblFooterR2;
    private javax.swing.JLabel lblFooterR3;
    private javax.swing.JLabel lblFooterR4;
    private javax.swing.JLabel lblFooterRTreasurer;
    private javax.swing.JLabel lblPayPeriod;
    private javax.swing.JLabel lblPayrollDesc1;
    private javax.swing.JLabel lblPayrollDesc2;
    private javax.swing.JLabel lblPayrollTitle;
    private javax.swing.JLabel lblSystemLogo;
    private javax.swing.JLabel lblTitleBot;
    private javax.swing.JLabel lblTitleMid;
    private javax.swing.JLabel lblTitleTop;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlFooterLeft;
    private javax.swing.JPanel pnlFooterRight;
    private javax.swing.JPanel pnlPayrollTable;
    private javax.swing.JPanel pnlPayrollTitle;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane scrpanePayrollTable;
    private javax.swing.JTable tblPayrollTable;
    // End of variables declaration//GEN-END:variables
}
