/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import payroll_system.dao.EmployeeDAO;
import payroll_system.dao.PayrollDAO;
import payroll_system.dao.EmployeeDeductionDAO;
import payroll_system.model.EmployeeDeduction;
import payroll_system.model.Employee;
import payroll_system.model.Payroll;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author Ong
 */
public class PayslipPopup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PayslipPopup.class.getName());
    // when a period is selected via the PeriodSelectionPopUp, store its id here
    private Integer selectedPeriodId = null;
    private boolean periodChosen = false;

    /**
     * Creates new form PayslipPopup
     */
    public PayslipPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        logoPlacer = new javax.swing.JLabel();
        payslip = new javax.swing.JLabel();
        titlePayPeriod = new javax.swing.JLabel();
        firstDate = new javax.swing.JLabel();
        secondDate = new javax.swing.JLabel();
        dash = new javax.swing.JLabel();
        employeeInfo = new javax.swing.JPanel();
        titleID = new javax.swing.JLabel();
        titleName = new javax.swing.JLabel();
        titlePosition = new javax.swing.JLabel();
        titleDate = new javax.swing.JLabel();
        employeeID = new javax.swing.JTextField();
        displayName = new javax.swing.JLabel();
        displayPosition = new javax.swing.JLabel();
        displayDate = new javax.swing.JLabel();
        Forms = new javax.swing.JPanel();
        netPayScrollPane = new javax.swing.JScrollPane();
        netPay = new javax.swing.JTable();
        mainFormScrollPane = new javax.swing.JScrollPane();
        mainForm = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payslip");
        setMinimumSize(new java.awt.Dimension(700, 650));
        setSize(new java.awt.Dimension(700, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPlacer.setText("System Logo");

        payslip.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        payslip.setText("Payslip");

        titlePayPeriod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titlePayPeriod.setText("PAY PERIOD:");

        firstDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstDate.setText("[MM,DD,YY]");

        secondDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        secondDate.setText("[MM,DD,YY]");

        dash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dash.setText("-");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(logoPlacer)
                        .addGap(169, 169, 169)
                        .addComponent(payslip))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(titlePayPeriod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondDate)))
                .addGap(51, 223, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payslip)
                    .addComponent(logoPlacer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePayPeriod)
                    .addComponent(firstDate)
                    .addComponent(dash)
                    .addComponent(secondDate))
                .addContainerGap())
        );

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 90));
        headerPanel.getAccessibleContext().setAccessibleName("");

        titleID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleID.setText("Employee ID: ");

        titleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleName.setText("Employee Name:");

        titlePosition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlePosition.setText("Employee Position:");

        titleDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleDate.setText("Date Issued:");

        employeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeIDActionPerformed(evt);
            }
        });

        displayName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        displayName.setText("[Employee Name]");

        displayPosition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        displayPosition.setText("[Employee Position]");

        displayDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        displayDate.setText("[MM/DD/YY]");

        javax.swing.GroupLayout employeeInfoLayout = new javax.swing.GroupLayout(employeeInfo);
        employeeInfo.setLayout(employeeInfoLayout);
        employeeInfoLayout.setHorizontalGroup(
            employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeInfoLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeInfoLayout.createSequentialGroup()
                        .addComponent(titlePosition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPosition))
                    .addGroup(employeeInfoLayout.createSequentialGroup()
                        .addComponent(titleID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(titleDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayDate))
                    .addGroup(employeeInfoLayout.createSequentialGroup()
                        .addComponent(titleName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayName)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        employeeInfoLayout.setVerticalGroup(
            employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeInfoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleID)
                    .addComponent(employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleDate)
                    .addComponent(displayDate))
                .addGap(18, 18, 18)
                .addGroup(employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleName)
                    .addComponent(displayName))
                .addGap(18, 18, 18)
                .addGroup(employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePosition)
                    .addComponent(displayPosition))
                .addGap(14, 14, 14))
        );

        getContentPane().add(employeeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 120));

        netPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        netPay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Net Pay", null}
            },
            new String [] {
                "Net Pay", "Amount"
            }
        ));
        netPay.setRowHeight(34);
        netPay.setShowGrid(true);
        netPayScrollPane.setViewportView(netPay);

        mainFormScrollPane.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        mainForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Rate per Month", "", "Tax (3% of gross)", null},
                {"Amount Accrued", "", "PAG-IBIG", null},
                {null, null, "SSS", null},
                {null, null, "Loan", null},
                {null, null, "Absences", null},
                {"Gross Pay", "", "Total Deductions", null}
            },
            new String [] {
                "Earnings", "Amount", "Deductions", "Amount"
            }
        ));
        mainForm.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        mainForm.setRowHeight(34);
        mainForm.setShowGrid(true);
        mainFormScrollPane.setViewportView(mainForm);

        javax.swing.GroupLayout FormsLayout = new javax.swing.GroupLayout(Forms);
        Forms.setLayout(FormsLayout);
        FormsLayout.setHorizontalGroup(
            FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormsLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(netPayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainFormScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        FormsLayout.setVerticalGroup(
            FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainFormScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(netPayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(Forms, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 700, 340));

        Back.setBackground(new java.awt.Color(11, 11, 69));
        Back.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Back.setLabel("BACK");
        Back.setPreferredSize(new java.awt.Dimension(148, 33));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, -1, -1));

        jButton3.setBackground(new java.awt.Color(11, 11, 69));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Select Period");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void employeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIDActionPerformed
        String idTxt = employeeID.getText().trim();
        if (idTxt.isEmpty()) {
            logger.info("No employee ID entered.");
            return;
        }

        try {
            int empId = Integer.parseInt(idTxt.replaceAll("[^0-9]", ""));

            EmployeeDAO empDao = new EmployeeDAO();
            Employee emp = empDao.getEmployeeById(empId);

            if (emp == null) {
                displayName.setText("[Employee Name]");
                displayPosition.setText("[Employee Position]");
                displayDate.setText("[MM/DD/YY]");
                // clear tables
                javax.swing.table.DefaultTableModel mf = (javax.swing.table.DefaultTableModel) mainForm.getModel();
                // reset amounts to empty
                for (int r = 0; r < mf.getRowCount(); r++) {
                    mf.setValueAt("", r, 1);
                    mf.setValueAt("", r, 3);
                }
                javax.swing.table.DefaultTableModel np = (javax.swing.table.DefaultTableModel) netPay.getModel();
                np.setValueAt("", 0, 1);

                javax.swing.JOptionPane.showMessageDialog(this, "Employee not found.", "Not found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            displayName.setText(emp.getEmpName());
            displayPosition.setText(emp.getEmpPosition());

            // Attempt to fetch latest payroll for this employee
            PayrollDAO payrollDAO = new PayrollDAO();
            List<Payroll> payrolls = payrollDAO.getPayrollByEmployee(empId);

            javax.swing.table.DefaultTableModel mf = (javax.swing.table.DefaultTableModel) mainForm.getModel();
            javax.swing.table.DefaultTableModel np = (javax.swing.table.DefaultTableModel) netPay.getModel();

            // clear previous amounts
            for (int r = 0; r < mf.getRowCount(); r++) {
                mf.setValueAt("", r, 1);
                mf.setValueAt("", r, 3);
            }
            np.setValueAt("", 0, 1);

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/yyyy");

            if (!payrolls.isEmpty()) {
                // If the pay period fields are filled, try to find the payroll that matches the entered period
                Payroll selectedPayroll = null;
                String p1 = firstDate.getText().trim();
                // If user left default placeholder or empty, ignore and use latest
                boolean periodEntered = !p1.isEmpty() && !p1.startsWith("[");

                DateTimeFormatter[] tryFormats = new DateTimeFormatter[] {
                    DateTimeFormatter.ofPattern("MM/dd/yyyy"),
                    DateTimeFormatter.ofPattern("MM-dd-yyyy"),
                    DateTimeFormatter.ofPattern("MM/dd/yy"),
                    DateTimeFormatter.ofPattern("MM-dd-yy")
                };

                java.time.LocalDate parsedStart = null;
                if (periodEntered) {
                    // try parsing the entered start date with multiple formats
                    for (DateTimeFormatter fmt : tryFormats) {
                        try {
                            parsedStart = java.time.LocalDate.parse(p1, fmt);
                            break;
                        } catch (Exception ex) {
                            // ignore and try next
                        }
                    }
                }

                if (parsedStart != null) {
                    // find payroll with matching period start (or same month/year)
                    for (Payroll pr : payrolls) {
                        if (pr.getPeriodStart() != null) {
                            if (pr.getPeriodStart().equals(parsedStart) ||
                                (pr.getPeriodStart().getMonth() == parsedStart.getMonth() && pr.getPeriodStart().getYear() == parsedStart.getYear())) {
                                selectedPayroll = pr;
                                break;
                            }
                        }
                    }
                }

                if (selectedPayroll == null) {
                    if (parsedStart != null) {
                        // user explicitly selected a period but no payroll exists for that employee in that period
                        javax.swing.JOptionPane.showMessageDialog(this,
                                "No payslip found for this employee in the selected period.",
                                "No Payslip", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        // leave tables cleared and exit
                        displayDate.setText("[MM/DD/YY]");
                        return;
                    } else {
                        // no period entered -> default to latest
                        selectedPayroll = payrolls.get(0);
                    }
                }

                Payroll p = selectedPayroll;

                // set the header pay period text fields to the payroll's period start/end
                if (p.getPeriodStart() != null) {
                    firstDate.setText(p.getPeriodStart().format(dtf));
                } else {
                    firstDate.setText("[MM/DD/YY]");
                }
                if (p.getPeriodEnd() != null) {
                    secondDate.setText(p.getPeriodEnd().format(dtf));
                } else {
                    secondDate.setText("[MM/DD/YY]");
                }

                // display period as issued date (end of period)
                if (p.getPeriodEnd() != null) {
                    displayDate.setText(p.getPeriodEnd().format(dtf));
                } else {
                    displayDate.setText("[MM/DD/YY]");
                }

                // Fill mainForm table: rate, accrued (gross), and deductions breakdown
                mf.setValueAt(String.format("%,.2f", emp.getRatePerDay()), 0, 1); // Rate per Month (show rate per day)
                mf.setValueAt(String.format("%,.2f", p.getGrossPay()), 1, 1); // Amount Accrued

                double gross = p.getGrossPay();
                // Tax is 3% of gross (as indicated by the column label)
                double tax = Math.round(gross * 0.03 * 100.0) / 100.0; // round to cents
                mf.setValueAt(String.format("%,.2f", tax), 0, 3);

                // Fetch employee-specific deductions and map to rows
                EmployeeDeductionDAO edao = new EmployeeDeductionDAO();
                java.util.List<EmployeeDeduction> dedList = edao.getDeductionsByEmployee(emp.getEmpId());

                // We'll try to map known deduction types to specific rows (pagibig, sss, loan, absences).
                // Any other deductions returned by the DAO will be placed into the remaining deduction rows
                // so the user can see the actual deduction name and amount.
                Double pagibig = null, sss = null, loan = null, absences = null;
                java.util.List<EmployeeDeduction> others = new java.util.ArrayList<>();

                for (EmployeeDeduction ed : dedList) {
                    String name = ed.getDeductionName() == null ? "" : ed.getDeductionName().toLowerCase();
                    double amt = ed.getDeductionAmount();
                    if (name.contains("pag") || name.contains("pag-") || name.contains("pagibig") || name.contains("pag ibig") || name.contains("hdmf")) {
                        pagibig = amt;
                    } else if (name.contains("sss")) {
                        sss = amt;
                    } else if (name.contains("loan")) {
                        loan = amt;
                    } else if (name.contains("absence") || name.contains("absences") || name.contains("absent")) {
                        absences = amt;
                    } else {
                        // keep unknown/other deduction entries to display below
                        others.add(ed);
                    }
                }

                // Populate deduction column amounts for the known rows (0-tax,1-pagibig,2-sss,3-loan,4-absences,5-total)
                if (pagibig != null) mf.setValueAt(String.format("%,.2f", pagibig), 1, 3);
                if (sss != null) mf.setValueAt(String.format("%,.2f", sss), 2, 3);
                if (loan != null) mf.setValueAt(String.format("%,.2f", loan), 3, 3);
                if (absences != null) mf.setValueAt(String.format("%,.2f", absences), 4, 3);

                // Fill remaining deduction rows with any 'other' deductions returned by DAO.
                // We'll place them starting at row 1..4 in the Deductions columns (col index 2 for name, 3 for amount)
                int[] targetRows = new int[] {1,2,3,4};
                int ti = 0;
                for (EmployeeDeduction ed : others) {
                    // find next free row (one that doesn't already have a value in column 3)
                    while (ti < targetRows.length) {
                        int rr = targetRows[ti];
                        Object existing = mf.getValueAt(rr, 3);
                        if (existing == null || (existing instanceof String && ((String) existing).trim().isEmpty())) {
                            // use this row
                            mf.setValueAt(ed.getDeductionName(), rr, 2);
                            mf.setValueAt(String.format("%,.2f", ed.getDeductionAmount()), rr, 3);
                            ti++;
                            break;
                        }
                        ti++;
                    }
                    if (ti >= targetRows.length) break; // no more space
                }

                // Gross row
                mf.setValueAt(String.format("%,.2f", gross), 5, 1);
                // Total Deductions (from payroll record)
                mf.setValueAt(String.format("%,.2f", p.getTotalDeductions()), 5, 3);

                // Net pay table
                np.setValueAt(String.format("%,.2f", p.getNetPay()), 0, 1);
            } else {
                // No payroll records yet: show current date and basic employee info
                displayDate.setText(java.time.LocalDate.now().format(dtf));
                // show rate per day
                mf.setValueAt(String.format("%,.2f", emp.getRatePerDay()), 0, 1);
                np.setValueAt("", 0, 1);
            }

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_employeeIDActionPerformed

    // Note: jTextField1 was removed; period is shown in header labels `firstDate`/`secondDate`.

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Open the period selection dialog so user can pick a pay period for the payslip
        PeriodSelectionPopUp dialog = new PeriodSelectionPopUp(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // After dialog closes, fetch chosen start/end and populate the payslip fields
        String start = dialog.getSelectedPeriodStart();
        String end = dialog.getSelectedPeriodEnd();
    String pid = dialog.getSelectedPeriodId();
        if (start != null && end != null) {
            // Format ISO date (YYYY-MM-DD) to the display format used elsewhere (MM/dd/yyyy)
            DateTimeFormatter displayFmt = DateTimeFormatter.ofPattern("MM/dd/yyyy");
            try {
                java.time.LocalDate s = java.time.LocalDate.parse(start);
                firstDate.setText(s.format(displayFmt));
            } catch (Exception ex) {
                try { firstDate.setText(start); } catch (Exception ignore) {}
            }
            try {
                java.time.LocalDate e = java.time.LocalDate.parse(end);
                secondDate.setText(e.format(displayFmt));
            } catch (Exception ex) {
                try { secondDate.setText(end); } catch (Exception ignore) {}
            }
            // store chosen period id so subsequent employee lookups respect this period
            try {
                if (pid != null) {
                    selectedPeriodId = Integer.parseInt(pid);
                    periodChosen = true;
                } else {
                    selectedPeriodId = null;
                    periodChosen = false;
                }
            } catch (NumberFormatException ex) {
                selectedPeriodId = null;
                periodChosen = false;
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PayslipPopup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel Forms;
    private javax.swing.JLabel dash;
    private javax.swing.JLabel displayDate;
    private javax.swing.JLabel displayName;
    private javax.swing.JLabel displayPosition;
    private javax.swing.JTextField employeeID;
    private javax.swing.JPanel employeeInfo;
    private javax.swing.JLabel firstDate;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel logoPlacer;
    private javax.swing.JTable mainForm;
    private javax.swing.JScrollPane mainFormScrollPane;
    private javax.swing.JTable netPay;
    private javax.swing.JScrollPane netPayScrollPane;
    private javax.swing.JLabel payslip;
    private javax.swing.JLabel secondDate;
    private javax.swing.JLabel titleDate;
    private javax.swing.JLabel titleID;
    private javax.swing.JLabel titleName;
    private javax.swing.JLabel titlePayPeriod;
    private javax.swing.JLabel titlePosition;
    // End of variables declaration//GEN-END:variables
}
