/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import payroll_system.dao.EmployeeDAO;
import payroll_system.dao.PayrollDAO;
import payroll_system.model.Employee;
import payroll_system.model.Payroll;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author Ong
 */
public class PayslipPopup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PayslipPopup.class.getName());

    /**
     * Creates new form PayslipPopup
     */
    public PayslipPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        logoPlacer = new javax.swing.JLabel();
        payslip = new javax.swing.JLabel();
        titlePayPeriod = new javax.swing.JLabel();
        firstDate = new javax.swing.JLabel();
        secondDate = new javax.swing.JLabel();
        dash = new javax.swing.JLabel();
        employeeInfo = new javax.swing.JPanel();
        titleID = new javax.swing.JLabel();
        titleName = new javax.swing.JLabel();
        titlePosition = new javax.swing.JLabel();
        titleDate = new javax.swing.JLabel();
        employeeID = new javax.swing.JTextField();
        displayName = new javax.swing.JLabel();
        displayPosition = new javax.swing.JLabel();
        displayDate = new javax.swing.JLabel();
        Forms = new javax.swing.JPanel();
        netPayScrollPane = new javax.swing.JScrollPane();
        netPay = new javax.swing.JTable();
        mainFormScrollPane = new javax.swing.JScrollPane();
        mainForm = new javax.swing.JTable();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payslip");
        setMinimumSize(new java.awt.Dimension(700, 650));
        setSize(new java.awt.Dimension(700, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPlacer.setText("System Logo");

        payslip.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        payslip.setText("Payslip");

        titlePayPeriod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titlePayPeriod.setText("PAY PERIOD:");

        firstDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstDate.setText("[MM,DD,YY]");

        secondDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        secondDate.setText("[MM,DD,YY]");

        dash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dash.setText("-");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(logoPlacer)
                        .addGap(169, 169, 169)
                        .addComponent(payslip))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(titlePayPeriod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondDate)))
                .addGap(51, 223, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payslip)
                    .addComponent(logoPlacer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePayPeriod)
                    .addComponent(firstDate)
                    .addComponent(dash)
                    .addComponent(secondDate))
                .addContainerGap())
        );

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 90));
        headerPanel.getAccessibleContext().setAccessibleName("");

        titleID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleID.setText("Employee ID: ");

        titleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleName.setText("Employee Name:");

        titlePosition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlePosition.setText("Employee Position:");

        titleDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleDate.setText("Date Issued:");

        employeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeIDActionPerformed(evt);
            }
        });

        displayName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        displayName.setText("[Employee Name]");

        displayPosition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        displayPosition.setText("[Employee Position]");

        displayDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        displayDate.setText("[MM/DD/YY]");

        javax.swing.GroupLayout employeeInfoLayout = new javax.swing.GroupLayout(employeeInfo);
        employeeInfo.setLayout(employeeInfoLayout);
        employeeInfoLayout.setHorizontalGroup(
            employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeInfoLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeInfoLayout.createSequentialGroup()
                        .addComponent(titlePosition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPosition))
                    .addGroup(employeeInfoLayout.createSequentialGroup()
                        .addComponent(titleID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(titleDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayDate))
                    .addGroup(employeeInfoLayout.createSequentialGroup()
                        .addComponent(titleName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayName)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        employeeInfoLayout.setVerticalGroup(
            employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeInfoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleID)
                    .addComponent(employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleDate)
                    .addComponent(displayDate))
                .addGap(18, 18, 18)
                .addGroup(employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleName)
                    .addComponent(displayName))
                .addGap(18, 18, 18)
                .addGroup(employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePosition)
                    .addComponent(displayPosition))
                .addGap(14, 14, 14))
        );

        getContentPane().add(employeeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 120));

        netPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        netPay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Net Pay", null}
            },
            new String [] {
                "Net Pay", "Amount"
            }
        ));
        netPay.setRowHeight(34);
        netPay.setShowGrid(true);
        netPayScrollPane.setViewportView(netPay);

        mainFormScrollPane.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        mainForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Rate per Month", "", "Tax (3% of gross)", null},
                {"Amount Accrued", "", "PAG-IBIG", null},
                {null, null, "SSS", null},
                {null, null, "Loan", null},
                {null, null, "Absences", null},
                {"Gross Pay", "", "Total Deductions", null}
            },
            new String [] {
                "Earnings", "Amount", "Deductions", "Amount"
            }
        ));
        mainForm.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        mainForm.setRowHeight(34);
        mainForm.setShowGrid(true);
        mainFormScrollPane.setViewportView(mainForm);

        javax.swing.GroupLayout FormsLayout = new javax.swing.GroupLayout(Forms);
        Forms.setLayout(FormsLayout);
        FormsLayout.setHorizontalGroup(
            FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormsLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(netPayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainFormScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        FormsLayout.setVerticalGroup(
            FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainFormScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(netPayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(Forms, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 700, 340));

        Back.setBackground(new java.awt.Color(11, 11, 69));
        Back.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Back.setLabel("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 120, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void employeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIDActionPerformed
        String idTxt = employeeID.getText().trim();
        if (idTxt.isEmpty()) {
            logger.info("No employee ID entered.");
            return;
        }

        try {
            int empId = Integer.parseInt(idTxt.replaceAll("[^0-9]", ""));

            EmployeeDAO empDao = new EmployeeDAO();
            Employee emp = empDao.getEmployeeById(empId);

            if (emp == null) {
                displayName.setText("[Employee Name]");
                displayPosition.setText("[Employee Position]");
                displayDate.setText("[MM/DD/YY]");
                // clear tables
                javax.swing.table.DefaultTableModel mf = (javax.swing.table.DefaultTableModel) mainForm.getModel();
                // reset amounts to empty
                for (int r = 0; r < mf.getRowCount(); r++) {
                    mf.setValueAt("", r, 1);
                    mf.setValueAt("", r, 3);
                }
                javax.swing.table.DefaultTableModel np = (javax.swing.table.DefaultTableModel) netPay.getModel();
                np.setValueAt("", 0, 1);

                javax.swing.JOptionPane.showMessageDialog(this, "Employee not found.", "Not found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            displayName.setText(emp.getEmpName());
            displayPosition.setText(emp.getEmpPosition());

            // Attempt to fetch latest payroll for this employee
            PayrollDAO payrollDAO = new PayrollDAO();
            List<Payroll> payrolls = payrollDAO.getPayrollByEmployee(empId);

            javax.swing.table.DefaultTableModel mf = (javax.swing.table.DefaultTableModel) mainForm.getModel();
            javax.swing.table.DefaultTableModel np = (javax.swing.table.DefaultTableModel) netPay.getModel();

            // clear previous amounts
            for (int r = 0; r < mf.getRowCount(); r++) {
                mf.setValueAt("", r, 1);
                mf.setValueAt("", r, 3);
            }
            np.setValueAt("", 0, 1);

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/yyyy");

            if (!payrolls.isEmpty()) {
                Payroll p = payrolls.get(0); // latest

                // display period as issued date (end of period)
                if (p.getPeriodEnd() != null) {
                    displayDate.setText(p.getPeriodEnd().format(dtf));
                } else {
                    displayDate.setText("[MM/DD/YY]");
                }

                // Fill mainForm table: rate, accrued (gross), gross, total deductions
                mf.setValueAt(String.format("%,.2f", emp.getRatePerDay()), 0, 1); // Rate per Month (show rate per day)
                mf.setValueAt(String.format("%,.2f", p.getGrossPay()), 1, 1); // Amount Accrued
                mf.setValueAt(String.format("%,.2f", p.getGrossPay()), 5, 1); // Gross Pay row
                mf.setValueAt(String.format("%,.2f", p.getTotalDeductions()), 5, 3); // Total Deductions amount

                // Net pay table
                np.setValueAt(String.format("%,.2f", p.getNetPay()), 0, 1);
            } else {
                // No payroll records yet: show current date and basic employee info
                displayDate.setText(java.time.LocalDate.now().format(dtf));
                // show rate per day
                mf.setValueAt(String.format("%,.2f", emp.getRatePerDay()), 0, 1);
                np.setValueAt("", 0, 1);
            }

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_employeeIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PayslipPopup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel Forms;
    private javax.swing.JLabel dash;
    private javax.swing.JLabel displayDate;
    private javax.swing.JLabel displayName;
    private javax.swing.JLabel displayPosition;
    private javax.swing.JTextField employeeID;
    private javax.swing.JPanel employeeInfo;
    private javax.swing.JLabel firstDate;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel logoPlacer;
    private javax.swing.JTable mainForm;
    private javax.swing.JScrollPane mainFormScrollPane;
    private javax.swing.JTable netPay;
    private javax.swing.JScrollPane netPayScrollPane;
    private javax.swing.JLabel payslip;
    private javax.swing.JLabel secondDate;
    private javax.swing.JLabel titleDate;
    private javax.swing.JLabel titleID;
    private javax.swing.JLabel titleName;
    private javax.swing.JLabel titlePayPeriod;
    private javax.swing.JLabel titlePosition;
    // End of variables declaration//GEN-END:variables
}
